In [27]:
import numpy as np
import time

In [18]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr)) # outputs n dimensional array

[1 2 3 4 5] <class 'numpy.ndarray'>


In [19]:
# comparison of execution performance
size = 100000000

py_list = list(range(size)) 
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list : {end-start} seconds")



np_arr = np.array(py_list)
start = time.time()
# vectorisation
sq_array = np_arr**2
end = time.time()
print(f"python array : {end-start} seconds")

python list : 16.126105070114136 seconds
python array : 0.514415979385376 seconds


In [20]:
# memory comparison
import sys
print(f"numpy array time = {sys.getsizeof(py_list) * len(py_list)} bytes")

numpy array time = 80000005600000000 bytes


In [25]:
# create from lists
arr2 = np.array([1,2,3,4,5,"prime"]) # will output the array as all strings
print(arr2, type(arr2) , arr2.dtype, arr2.shape)
#U21 means values in array are stored as strings 
#(6,) means 1 by 6 dimensions // 6 vals in array

arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]]) # only outputs rectangular arrays
print(arr3, type(arr3), arr3.shape)

['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3)


In [47]:
arr4 = np.zeros((2, 3), dtype="int64") #prefills integers
print(arr4, arr4.shape) # creating 0 matrix of size 2 by 3

arr5 = np.ones((2, 3), dtype="int64")
print(arr5, arr5.shape)

arr6 = np.full((3, 3), 67)
print(arr6, arr6.shape)

arr7 = np.eye((3), dtype="int64")
print(arr7, arr7.shape)

arr8 = np.arange(0, 11, 2) # matrix of even ints from 0 to n-1 by ranging elements
print(arr8, arr8.shape)

arr9 = np.linspace(1, 100, 4) # evenly spaced arrays
print(arr9, arr9.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[67 67 67]
 [67 67 67]
 [67 67 67]] (3, 3)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [54]:
# properties of numpy arrays
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size) # nō of elements
print(arr.dtype)
print(arr.ndim) #2D array so 2 in this case

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype) #turns og arr into a float array

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [57]:
# ops on arrays
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape(3,2)
print(reshaped, reshaped.shape) #we can only reshape when nō of elements is compatible

flattened = arr.flatten() # 2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [66]:
# index array
arr = np.array([1,2,3,4,5])
print(arr[0]) #1
print(arr[3]) #4

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2[1,2]) #6
print(arr2[2][1]) #8

#fancy indexing
arr3 = np.array([1,2,3,4,5])

idx = [0,1,3]
print(arr3[idx]) # ouputs corresponding elements to the index vals

#boolean indexing
arr4 = np.array([1,2,3,4,5])

print(arr4[arr4>2]) #vals > 2
print(arr4[arr4%2 == 0]) #even vals
print(arr4[arr4%2 != 0]) #odd vals

1
4
6
8
[1 2 4]
[3 4 5]
[2 4]
[1 3 5]


In [74]:
#slicing
arr = np.array([1,2,3,4,5])
# format : [start, end, step]

print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[:])
print(arr[::2]) #alternating elements
# when slicing numpy array - much faster because it only takes a view of the og array instead of creating
# a copy when slicing a python array

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]


In [78]:
# copy vs view
# nums = [1,2,3,4,5]
# sub_list = nums[1:3]
# print(sub_list)
# sub_list[0] = 200

# print(sub_list)
# print(nums)

arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3]
print(sub_arr)

sub_arr[0] = 200
print(sub_arr)
print(arr) # we subbed the val 2 for 200 and in the numpy array we haven't created 
# a copy and the og array is also affected

# copy view of sliced array into variable using .copy

[2 3]
[200   3]
[  1 200   3   4   5]


In [84]:
# data types 
arr = np.array([1,2,3.14,4,5, "prime"])
print(arr, arr.dtype)


arr1 = np.array([3+5j])
arr2 = np.array([6+7j])
print(arr1 + arr2)
print(arr1 - arr2)

arr3 = np.array(["prime", {1,2,3}, 3.14])
print(arr3, arr3.dtype)

['1' '2' '3.14' '4' '5' 'prime'] <U32
[9.+12.j]
[-3.-2.j]
['prime' {1, 2, 3} 3.14] object


In [88]:
#1D -> 1 axis(axis 0)
#2D -> 2 axes(axis 0 -> rows -> vertically)
#(axis 1 -> columns -> horizontally)
#3D -> 3 axes(axis 0 -> depth/layers)
#(axis 1 -> row in each layer)
#(axis 2 -> column)

#multidimensional array
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(arr2D))
sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)
sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)
print(arr2D[0:2, 1:2])

45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [95]:
#3D arrays

arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) #2 x 3 x 2
print(arr3D, arr3D.shape)
print(arr3D[1,1,0])
#slicing
print(arr3D[:,0,:]) # first rwo from both layers
print(arr3D[:,:,0]) # first column from both layers

arr3D[:,0,:] = 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [98]:
#vectorisation

arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr**2)
print(arr+10)
print(arr+arr2)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]


In [104]:
# broadcasting is scaling i.e., diff sized arrays
# two dimensions are compatible when 1. they are equal or 2. one of them is 1
arr = np.array([1,2,3,4,5])
print(arr+5)
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr.shape)
print(arr2.shape)
print(arr+arr2)

[ 6  7  8  9 10]
(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [114]:
# vector normalisation -> (array - mean)/std dev
#std dev = √(sum(val-mean)^2/N)
# normalise

arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
std_dev = np.std(arr)

normalised_arr = (arr-mean)/std_dev
print(normalised_arr) # mean = 0 and std will be close to as 1 as possible

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [113]:
arr = np.array([1,4,6,6,-3,5,7,5,3,2,5,6,8])
print(np.unique(arr)) # removes dupes
print(np.abs(arr))
print(np.sort(arr)) # puts them in order

[-3  1  2  3  4  5  6  7  8]
[1 4 6 6 3 5 7 5 3 2 5 6 8]
[-3  1  2  3  4  5  5  5  6  6  6  7  8]
